package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.43

import (
	"context"
	"errors"
	gql "scriptura/scriptura-api/graphql/.generated"
	"scriptura/scriptura-api/models"
)

// Book is the resolver for the book field.
func (r *queryResolver) Book(ctx context.Context, input gql.BookInput) (*models.Book, error) {
	book, err := r.AppRepository.BookRepository.GetBook(input.ID)
	if book.Id == 0 {
		return nil, errors.New("book not found")
	}
	return &book, err
}

// Query returns gql.QueryResolver implementation.
func (r *Resolver) Query() gql.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
